INSERT INTO SALESPEOPLE (FIRST_NAME, LAST_NAME, EMAIL, PHONE, ADDRESS, CITY, STATE, ZIPCODE) VALUES ('Benjamin','Sims','bsimsi@hplussport.com','(502)297-0499','42 Johnson Center','Louisville','KY','40298');

INSERT INTO PRODUCTS (PRODUCT_ID, NAME, SIZE, VARIETY, PRICE, STATUS) VALUES('MWBLU20','Mineral Water',20,'Blueberry',1.79,'ACTIVE');
INSERT INTO PRODUCTS (PRODUCT_ID, NAME, SIZE, VARIETY, PRICE, STATUS) VALUES('MWBLU32','Mineral Water',32,'Blueberry',3.69,'ACTIVE');
INSERT INTO PRODUCTS (PRODUCT_ID, NAME, SIZE, VARIETY, PRICE, STATUS) VALUES('MWLEM20','Mineral Water',20,'Lemon-Lime',1.79,'ACTIVE');
INSERT INTO PRODUCTS (PRODUCT_ID, NAME, SIZE, VARIETY, PRICE, STATUS) VALUES('MWLEM32','Mineral Water',32,'Lemon-Lime',3.69,'ACTIVE');
INSERT INTO PRODUCTS (PRODUCT_ID, NAME, SIZE, VARIETY, PRICE, STATUS) VALUES('MWORG20','Mineral Water',20,'Orange',1.79,'ACTIVE');
INSERT INTO PRODUCTS (PRODUCT_ID, NAME, SIZE, VARIETY, PRICE, STATUS) VALUES('MWORG32','Mineral Water',32,'Orange',3.69,'ACTIVE');
INSERT INTO PRODUCTS (PRODUCT_ID, NAME, SIZE, VARIETY, PRICE, STATUS) VALUES('MWPEA20','Mineral Water',20,'Peach',1.79,'ACTIVE');
INSERT INTO PRODUCTS (PRODUCT_ID, NAME, SIZE, VARIETY, PRICE, STATUS) VALUES('MWPEA32','Mineral Water',32,'Peach',3.69,'ACTIVE');
INSERT INTO PRODUCTS (PRODUCT_ID, NAME, SIZE, VARIETY, PRICE, STATUS) VALUES('MWRAS20','Mineral Water',20,'Raspberry',1.79,'ACTIVE');
INSERT INTO PRODUCTS (PRODUCT_ID, NAME, SIZE, VARIETY, PRICE, STATUS) VALUES('MWRAS32','Mineral Water',32,'Raspberry',3.69,'ACTIVE');
INSERT INTO PRODUCTS (PRODUCT_ID, NAME, SIZE, VARIETY, PRICE, STATUS) VALUES('MWSTR20','Mineral Water',20,'Strawberry',1.79,'ACTIVE');
INSERT INTO PRODUCTS (PRODUCT_ID, NAME, SIZE, VARIETY, PRICE, STATUS) VALUES('MWSTR32','Mineral Water',32,'Strawberry',3.69,'ACTIVE');
INSERT INTO PRODUCTS (PRODUCT_ID, NAME, SIZE, VARIETY, PRICE, STATUS) VALUES('MWCRA20','Mineral Water',20,'Cranberry',1.79,'DISCONTINUED');
INSERT INTO PRODUCTS (PRODUCT_ID, NAME, SIZE, VARIETY, PRICE, STATUS) VALUES('MWCRA32','Mineral Water',32,'Cranberry',3.69,'DISCONTINUED');
INSERT INTO PRODUCTS (PRODUCT_ID, NAME, SIZE, VARIETY, PRICE, STATUS) VALUES('MWMAN20','Mineral Water',20,'Mango',1.79,'DISCONTINUED');
INSERT INTO PRODUCTS (PRODUCT_ID, NAME, SIZE, VARIETY, PRICE, STATUS) VALUES('MWMAN32','Mineral Water',32,'Mango',3.69,'DISCONTINUED');

INSERT INTO CUSTOMERS (FIRST_NAME, LAST_NAME, EMAIL, PHONE, ADDRESS, CITY, STATE, ZIPCODE) VALUES ('Timothy','Kim','tkimps@sciencedirect.com','(248)248-4484','8 Montana Park','Detroit','MI','48258');
INSERT INTO CUSTOMERS (FIRST_NAME, LAST_NAME, EMAIL, PHONE, ADDRESS, CITY, STATE, ZIPCODE) VALUES ('Carol','Shaw','cshaw0@mlb.com','(206)804-8771','8157 Longview Court','Seattle','WA','98121');

INSERT INTO ORDERS(ORDER_ID, CUSTOMER_ID, SALESPERSON_ID) VALUES ('H2-1203', (SELECT CUSTOMER_ID FROM CUSTOMERS WHERE EMAIL = 'tkimps@sciencedirect.com'), (SELECT SALESPERSON_ID FROM SALESPEOPLE WHERE EMAIL = 'bsimsi@hplussport.com'));
INSERT INTO ORDERS(ORDER_ID, CUSTOMER_ID, SALESPERSON_ID) VALUES ('H2-1204', (SELECT CUSTOMER_ID FROM CUSTOMERS WHERE EMAIL = 'cshaw0@mlb.com'), (SELECT SALESPERSON_ID FROM SALESPEOPLE WHERE EMAIL = 'bsimsi@hplussport.com'));


INSERT INTO ORDER_LINES (ORDER_ID, PRODUCT_ID, QUANTITY) VALUES ('H2-1203', 'MWBLU20', 4);
INSERT INTO ORDER_LINES (ORDER_ID, PRODUCT_ID, QUANTITY) VALUES ('H2-1203', 'MWSTR32', 2);

INSERT INTO ORDER_LINES (ORDER_ID, PRODUCT_ID, QUANTITY) VALUES ('H2-1204', 'MWCRA32', 2);
INSERT INTO ORDER_LINES (ORDER_ID, PRODUCT_ID, QUANTITY) VALUES ('H2-1204', 'MWMAN20', 6);